spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace